language: go
go:
  - "1.12"

env:
  # needed for the snap pipe:
  - PATH=/snap/bin:$PATH

before_install:
  - go get -u golang.org/x/lint/golint
script:
  - make lint
  - make test

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux